### ISSUE TITLE
[CLI] Add download support back for older models

### ISSUE THREAD

**Issue by xNul** [meta-llama/llama-toolchain#21]
The [CLI Reference](https://github.com/meta-llama/llama-toolchain/blob/main/docs/cli_reference.md) shows how it was possible to download and run older models such as Llama 2 with the CLI, but with a recent commit, it isn't possible to download any model older than the Llama 3.1 family. Can we get support re-added for downloading older models like Llama 2, Code Llama, etc?

I've opened https://github.com/meta-llama/llama-models/issues/83 as well because it seems to be where models are being sourced from now.

**Comment by dltn** [comment]
Thanks for the suggestion! Addressed in https://github.com/meta-llama/llama-models/commit/3214718f53deec534b9529266e860e84dfb60d2f.
